### ISSUE TITLE
Adding Library Path to DYLD_LIBRARY_PATH in Windows

### ISSUE THREAD

**Issue by tongap3** [misterwindupbird/IBO#1]
@misterwindupbird When I run demo.py, my call stops before plots are generated and iterative updates are provided. The issue is that lpath is not found for cdirectGP, which is called by maximizeEI in demo.py. I want to make sure that I have properly added the library path to my DYLD_LIBRARY_PATH. I am running on Windows and currently have some failures when I run the unittests in the ego folder. 

![unittest failures](https://cloud.githubusercontent.com/assets/20278440/16555214/ce45f13e-41d3-11e6-83d7-7fad564e72f7.png)

There is not a libs file or subfolder in the cpp folder. Currently, what am I doing by adding .../cpp/libs/ to my DYLD_LIBRARY_PATH?

I am new to GitHub (and BitBucket) and I am just starting to use python again (after taking one semester in python 4 years ago). I really appreciate any advice and insights that could be provided. Thank you.

**Comment by misterwindupbird** [comment]
Unfortunately I have never run this code on Windows, only OSX and Linux. On those systems setting DYLD_LIBRARY_PATH will tell the ctypes module where to look for the C++ library `libego` that the Makefile builds. I don't know how to build & call the library on Windows.

The demos expect to find the libego library and will fail if they don't. However, it it possible to run the demos without the library. In `demoObservations()` change the line

`_, optx = maximizeEI(GP, bound, xi=.1)
`
to
`_, optx = maximizeEI(GP, bound, xi=.1, useCDIRECT=False)
` 

You should be able to do the same thing elsewhere if there are other methods that expect the library.

I've confirmed this works on OSX to run the demo without the library. I think it should work for Windows, too, but I can't promise it will.

(I also added some other minor fixes, so please do a git pull to get the updated version.)

**Comment by tongap3** [comment]
@misterwindupbird I reran the code by changing the line that you mentioned and it worked! I have not done a git pull to get your updated version, but I can try that as well.

Thank you!
